name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

    - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@191986574c0735ffad7ae1a297a414d6e6f95375
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.BDXSEC_CN_SSH_PRIVATE_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.BDXSEC_CN_HOST }}
        # Remote user
        REMOTE_USER: ${{ secrets.BDXSEC_CN_USER }}
        # Source directory
        SOURCE: "_site" # optional, default is 
        # Target directory
        TARGET: ${{ secrets.BDXSEC_CN_WEB_PATH }}
        # Arguments to pass to rsync
        ARGS: "-rltgoDzvO" # optional, default is -rltgoDzvO
